services:
  db:
    image: mysql:8.0
    container_name: gametracker_db
    environment:
      # On met "root" partout pour aligner avec le code Python
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gametracker
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - gametracker_db_data:/var/lib/mysql
    healthcheck:
      # Le test vérifie que root peut se connecter
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: gametracker_app
    depends_on:
      db:
        condition: service_healthy
    # On force Python à utiliser ces infos (Sécurité anti-bug)
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=gametracker
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./output:/app/output
    restart: on-failure

volumes:
  gametracker_db_data: